[pytest]
testpaths = tests

filterwarnings =
    ignore::DeprecationWarning:pkg_resources.*:
    ignore::DeprecationWarning:distutils.*:
    ignore::DeprecationWarning:torch.utils.tensorboard.*:
    ignore::DeprecationWarning:pytorch_lightning.*:

markers =
    gui: marks GUI integration tests
    gpu: marks tests that require GPU (deselect with '-m "not gpu"')

# Skip GPU tests by default
addopts = -m "not gpu"

qt_api = pyside6

python_functions = test_* *_test gpu_test_*

# Configure test ordering - GPU tests will run last
python_classes = Test* *Test
python_files = test_*.py *_test.py
