name: GPU Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gpu-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Install FFMPEG
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install PySide2
      run: |
        python -m pip install --upgrade pip
        pip install "pyside2==5.13.2"

    - name: Install PyTorch with CUDA
      run: |
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cu102

    - name: Install package and test dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov
        python setup.py develop

    - name: GPU Tests
      run: |
        pytest -v -m "gpu" tests/
      env:
        CUDA_VISIBLE_DEVICES: 0
